version: "3.2"

services:
  database:
    image: postgres
    container_name: database_estabelecimentos
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=estabelecimentos
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
