version: "3.8"

services:
  app:
    build: .
    container_name: estabelecimentos_api
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/app
volumes:
  pgdata:
    driver: local
